before_commands:
    - "composer install --no-dev --prefer-source"

filter:
    paths:
        - src/*
        - tests/*

tools:
    external_code_coverage:
        timeout: 1200
    php_code_coverage:
        enabled: true
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
    php_cpd:
        enabled: true
    php_cs_fixer:
        enabled: true
        config:
            level: all
    php_loc:
        enabled: true
    php_mess_detector:
        enabled: true
    php_pdepend:
        enabled: true
    php_analyzer:
        enabled: true
    php_hhvm:
        enabled: true
    sensiolabs_security_checker: true
