language: php

cache:
  directories:
    - vendor
    
php:
  - 5.5
  - 5.6
  - 7
  - hhvm
  - hhvm-nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm-nightly
    
before_script:
  - composer update --prefer-dist
  
script:
  - if [ $TRAVIS_PHP_VERSION = '5.6' ]; then PHP_CS_FIXER_FLAGS="fix -v --dry-run --diff --config-file=.php_cs"; else PHP_CS_FIXER_FLAGS="help"; fi  
  - vendor/bin/phpunit --coverage-clover=coverage.clover
  - vendor/bin/php-cs-fixer ${PHP_CS_FIXER_FLAGS}

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
