language: php

php:
  - 5.5
  - 5.6
  - nightly
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm-nightly
    
before_script:
  - composer update --prefer-dist
  
script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover
  - vendor/bin/php-cs-fixer fix -v --dry-run

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
